# 实验唯一标识串
_key_:
  model: m
  optimizer/lr: lr
  DataLoader/batch_size: bs
  optimizer/weight_decay: wd
  sample_group_size: nss
  sample_top_size: sts
  sample_policy: nsp
  drop: drop
  loss/function: loss
  dataset/index_by_user: ibu
  dataset/noise: noise
  dataset/noise_p: noiseP
  train/softw_enable: stw
  sample_ig/enable: ig
  sample_ig/alpha: iga

# 在 pipeline 中使用
model: GMF
dim: 32
drop: 0.1
log_folder: "exps"
log_tag: "GMF"
cuda: "3"
seed: "random"
evaluator_time: 10
evaluator_args:
  stop_delay: 300
  use_stop: False
  eval_xs: [1, 3]
epochs: 10000
sample_group_size: 32
sample_group_size_pos: 32
sample_group_size_neg: 32
sample_policy: Nmax
sample_top_size: 32
sample_ig:
  enable: True
  alpha: 0.0
  post_un_loss: True
  cache_times: 2
train:
  epoch_tqdm: True
  batch_tqdm: False
  print_eval: False
  softw_enable: False
dataset:
  index_by_user: True
  noise: True
  noise_p: 0.15
DataLoader:
  shuffle: False
  batch_size: 1024
  drop_last: False
  pin_memory: False
optimizer:
  lr: 0.12
  weight_decay: 2.4
loss:
  function: relu # relu / logistic
# log as tee file
logfile: True
