# 实验唯一标识串
_key_:
  model: m
  optimizer/lr: lr
  DataLoader/batch_size: bs
  optimizer/weight_decay: wd
  sample_group_size: nss
  sample_top_size: sts
  sample_policy: nsp
  drop: drop
  loss/function: loss
  dataset/index_by_user: ibu
  dataset/noise: no
  dataset/noise_p: nop
  train/softw_enable: stw

# 在 pipeline 中使用
model: GMF
dim: 32
drop: 0.1
log_folder: "exps"
log_tag: "GMF"
cuda: "3"
seed: "random"
evaluator_time: 10
evaluator_args:
  stop_delay: 300
  use_stop: False
epochs: 10000
sample_group_size: 32
sample_policy: Nmax
sample_top_size: 32
train:
  epoch_tqdm: True
  batch_tqdm: False
  print_eval: False
  softw_enable: True
dataset:
  index_by_user: True
  noise: True
  noise_p: 0.05
DataLoader:
  shuffle: False
  batch_size: 6028
  drop_last: False
  pin_memory: False
optimizer:
  lr: 0.09
  weight_decay: 4.8
loss:
  function: relu # relu / logistic
# log as tee file
logfile: True
