# 实验唯一标识串
_key_:
  model: m
  optimizer/lr: lr
  DataLoader/batch_size: bs
#  optimizer/weight_decay: wd
  sample_group_size: nss
  sample_top_size: sts
  sample_policy: nsp

# 在 pipeline 中使用
model: GMF
dim: 32
log_folder: "exps"
log_tag: "GMF"
cuda: "3"
seed: "random"
evaluator_time: 3
evaluator_args:
  stop_delay: 5
epochs: 1000
sample_group_size: 32
sample_policy: Nmax
sample_top_size: 16
DataLoader:
  shuffle: True
  batch_size: 1024
  drop_last: True
  pin_memory: False
optimizer:
  lr: 0.3
  weight_decay: 0
# log as tee file
logfile: True